// Defining constants for actions and reducers

const GET_VIDEO_LIST = 'GET_VIDEO_LIST';
const GET_VIDEO_LIST_SUCCESS = 'GET_VIDEO_LIST_SUCCESS';
const GET_CURRENT_VIDEO = 'GET_CURRENT_VIDEO';
const GET_CURRENT_VIDEO_SUCCESS = 'GET_CURRENT_VIDEO_SUCCESS';

export default {
  GET_VIDEO_LIST,
  GET_VIDEO_LIST_SUCCESS,
  GET_CURRENT_VIDEO,
  GET_CURRENT_VIDEO_SUCCESS,
};
